In [1]:
import pandas as pd

In [2]:
from data_formatter import collect_and_format_data, format_data
from Operations import *

In [3]:

pc = PercentChange(['bb_upper'])

In [4]:
df = collect_and_format_data(
    "test_0",
    [ RemoveColumns(['time','atr',"bb_upper","bb_middle","bb_lower"]), pc],
    column_merge_mode='merge',
    write_csv=True,
)

Skipping.. RemoveColumns for ANET2025-08-12.csv
Skipping.. PercentChange for ANET2025-08-12.csv
Skipping.. PercentChange for RVNL.NS2025-08-12.csv
Skipping.. PercentChange for strange.csv

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   action          1530 non-null   object
 1   close           1530 non-null   float64
 2   open            1529 non-null   float64
 3   high            1530 non-null   float64
 4   low             1530 non-null   float64
 5   volume          1530 non-null   int64
 6   price           1530 non-null   float64
 7   fast_ema        1530 non-null   float64
 8   slow_ema        1530 non-null   float64
 9   rsi_14          1530 non-null   float64
 10  vwma            1530 non-null   float64
 11  action_quality  1530 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 143.6+ KB

In [6]:
_df = df

In [7]:
df = format_data(df,operations=[RemoveEmptyNullRows()])

In [8]:
df

,action,close,open,high,low,volume,price,fast_ema,slow_ema,rsi_14,vwma,action_quality
0,hold,138.500000,138.544998,139.085098,138.279999,212860.0,138.500000,0.000000,0.000000,50.000000,138.500000,good
1,hold,138.270004,138.639999,138.800003,138.199997,28967.0,138.270004,0.000000,0.000000,50.000000,138.472450,neutral
2,hold,138.990005,138.270004,139.000000,138.254593,33886.0,138.990005,0.000000,0.000000,50.000000,138.536059,good
3,hold,138.910004,139.074997,139.110001,138.789993,21643.0,138.910004,0.000000,0.000000,50.000000,138.563277,neutral
4,hold,139.695007,138.970001,139.725006,138.910004,36273.0,139.695007,0.000000,0.000000,50.000000,138.686321,good
...,...,...,...,...,...,...,...,...,...,...,...,...
1525,hold,326.250000,326.149994,326.299988,325.600006,77197.0,326.250000,327.688035,331.070103,25.721164,329.585170,neutral
1526,hold,326.250000,326.250000,326.850006,326.000000,78862.0,326.250000,327.400428,330.631912,25.721164,329.446522,neutral
1527,hold,323.700012,326.500000,326.649994,323.700012,195146.0,323.700012,326.660345,330.001739,21.132866,329.004236,neutral
1528,hold,322.250000,323.649994,324.000000,322.000000,157694.0,322.250000,325.778276,329.297035,19.051673,328.616187,neutral
1529,hold,323.450012,322.200012,323.500000,322.000000,170764.0,323.450012,325.312623,328.765488,25.583323,328.306828,neutral

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   action          1529 non-null   object
 1   close           1529 non-null   float64
 2   open            1529 non-null   float64
 3   high            1529 non-null   float64
 4   low             1529 non-null   float64
 5   volume          1529 non-null   float64
 6   price           1529 non-null   float64
 7   fast_ema        1529 non-null   float64
 8   slow_ema        1529 non-null   float64
 9   rsi_14          1529 non-null   float64
 10  vwma            1529 non-null   float64
 11  action_quality  1529 non-null   object
dtypes: float64(10), object(2)
memory usage: 143.6+ KB

In [10]:
_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   action          1529 non-null   object
 1   close           1529 non-null   float64
 2   open            1529 non-null   float64
 3   high            1529 non-null   float64
 4   low             1529 non-null   float64
 5   volume          1529 non-null   float64
 6   price           1529 non-null   float64
 7   fast_ema        1529 non-null   float64
 8   slow_ema        1529 non-null   float64
 9   rsi_14          1529 non-null   float64
 10  vwma            1529 non-null   float64
 11  action_quality  1529 non-null   object
dtypes: float64(10), object(2)
memory usage: 143.6+ KB

In [11]:
from Scaler import STDScaler, WeightedLabelScaler
d1 = df.copy()
d2 = df.copy()

In [12]:
s1 = STDScaler()
s2 = WeightedLabelScaler()

In [13]:
sc_d1 = s1.fit_transform(d1)
sc_d2 = s2.fit_transform(d2)

Warning: Some rows have missing values!
Warning: Some rows have missing values!

In [14]:
s1.categoricalCols

['action', 'action_quality']

In [15]:
s1.getNumericCols()

['close',
 'open',
 'high',
 'low',
 'volume',
 'price',
 'fast_ema',
 'slow_ema',
 'rsi_14',
 'vwma']

In [16]:
sc_d1.head()

,action,close,open,high,low,volume,price,fast_ema,slow_ema,rsi_14,vwma,action_quality
0,1,-0.994375,-0.993904,-0.989372,-0.995768,6.055830,-0.994375,-2.206558,-2.017511,-0.057602,-0.986711,2
1,1,-0.996638,-0.992969,-0.992176,-0.996556,0.417719,-0.996638,-2.206558,-2.017511,-0.057602,-0.986981,4
2,1,-0.989552,-0.996610,-0.990209,-0.996018,0.568534,-0.989552,-2.206558,-2.017511,-0.057602,-0.986358,2
3,1,-0.990339,-0.988689,-0.989127,-0.990745,0.193167,-0.990339,-2.206558,-2.017511,-0.057602,-0.986091,4
4,1,-0.982613,-0.989722,-0.983079,-0.989563,0.641719,-0.982613,-2.206558,-2.017511,-0.057602,-0.984885,2

In [17]:
s1.save('stdscale_r')

In [18]:
loaded_scaler = STDScaler()

In [19]:
loaded_scaler.load('stdscale_r')

In [21]:
loaded_scaler.numericCols

['close',
 'open',
 'high',
 'low',
 'volume',
 'price',
 'fast_ema',
 'slow_ema',
 'rsi_14',
 'vwma']

In [22]:
s2.save("s2")

In [23]:
test = WeightedLabelScaler()
test.load('s2')

In [24]:
test.categoricalCols

['action', 'action_quality']